# Generated by Django 5.1.1 on 2024-11-25 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0004_project_vtex_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("purchased", "Purchased"),
                            ("delivered_success", "Delivered Success"),
                            ("delivered_error", "Delivered Error"),
                            ("empty", "Empty"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Status of Cart",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("config", models.JSONField(default=dict)),
                ("abandoned", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vtex_cart",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartNotificationQueue",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Notification Status",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_queue",
                        to="vtex.cart",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["project", "status"], name="vtex_cart_project_da4d1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartnotificationqueue",
            index=models.Index(
                fields=["status", "created_on"], name="vtex_cartno_status_1942e9_idx"
            ),
        ),
    ]
