# Generated by Django 5.1.1 on 2024-11-22 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0004_project_vtex_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("purchased", "Purchased"),
                            ("abandoned", "Abandoned"),
                            ("delivered success", "Delivered Success"),
                            ("delivered error", "Delivered Error"),
                            ("empty", "Empty"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Status of Cart",
                    ),
                ),
                ("phone_number", models.CharField(max_length=256)),
                ("config", models.JSONField(default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vtex_cart",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
