# Generated by Django 5.1.1 on 2025-07-03 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0018_feature_code"),
        ("vtex", "0002_rename_cart_id_cart_order_form_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="flows_channel_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="cart",
            name="whatsapp_click_id",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="integrated_feature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts_by_feature",
                to="features.integratedfeature",
            ),
        ),
    ]
