# Generated by Django 5.1.1 on 2025-06-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vtex", "0002_rename_cart_id_cart_order_form_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="whatsapp_click_id",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
