# Generated by Django 5.1.1 on 2025-08-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vtex", "0004_alter_cart_status_cart_vtex_cart_order_f_7d9461_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="capi_notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
