# Generated by Django 5.1.1 on 2025-09-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vtex", "0005_cart_capi_notification_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="flows_channel_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
