# Generated by Django 5.1.1 on 2025-09-03 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0022_integratedagent_global_rule_prompt"),
        ("vtex", "0006_alter_cart_flows_channel_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="integrated_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts_by_agent",
                to="agents.integratedagent",
            ),
        ),
    ]
