# Generated by Django 5.2.12 on 2026-03-13 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_projectonboarding_skipped_and_more"),
        ("vtex", "0008_alter_cart_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("vtex_account", models.CharField(max_length=100, unique=True)),
                ("plan", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, default="", max_length=20)),
                ("data", models.JSONField(default=dict)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vtex_account"], name="vtex_lead_vtex_ac_d26b55_idx"
                    )
                ],
            },
        ),
    ]
