# Generated by Django 5.1.1 on 2026-04-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vtex", "0009_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("purchased", "Purchased"),
                    ("delivered_success", "Delivered Success"),
                    ("delivered_error", "Delivered Error"),
                    ("empty", "Empty"),
                    ("skipped_identical_cart", "Skipped Identical Cart"),
                    (
                        "skipped_abandoned_cart_cooldown",
                        "Skipped Abandoned Cart Cooldown",
                    ),
                    ("skipped_below_minimum_value", "Skipped Below Minimum Value"),
                    (
                        "skipped_order_form_already_notified",
                        "Skipped Order Form Already Notified",
                    ),
                ],
                default="created",
                max_length=50,
                verbose_name="Status of Cart",
            ),
        ),
    ]
