# Generated by Django 5.1.1 on 2026-05-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vtex", "0010_alter_cart_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="notification_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the abandonment notification was successfully sent",
                null=True,
            ),
        ),
    ]
