# Generated by Django 5.2.16 on 2026-08-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0029_integratedagent_integer_pk"),
        ("features", "0018_feature_code"),
        ("projects", "0015_projectonboarding_is_active_and_managers"),
        ("vtex", "0011_integratedagent_integer_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="notification_order_form_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
