# Generated by Django 5.2.16 on 2026-09-02 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0015_projectonboarding_is_active_and_managers"),
        ("vtex", "0013_cart_notification_order_form_id_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackInStockWaiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("sku_id", models.CharField(max_length=64)),
                ("phone", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("seller", models.CharField(max_length=64)),
                ("sales_channel", models.CharField(max_length=64)),
                ("locale", models.CharField(default="pt-BR", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_details", models.JSONField(blank=True, default=list)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="back_in_stock_waiters",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "status", "sku_id"],
                        name="vtex_backin_project_c3be43_idx",
                    ),
                    models.Index(
                        fields=["status", "sent_at"],
                        name="vtex_backin_status_147f4c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "project",
                            "sku_id",
                            "phone",
                            "seller",
                            "sales_channel",
                        ),
                        name="uniq_back_in_stock_waiter_offer",
                    )
                ],
            },
        ),
    ]
