# Generated by Django 5.2.16 on 2026-09-10 19:43

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("vtex", "0014_back_in_stock_waiter"),
    ]

    operations = [
        migrations.AddField(
            model_name="backinstockwaiter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="backinstockwaiter",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sending", "Sending"),
                    ("notifying", "Notifying"),
                    ("sent", "Sent"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
