# Generated by Django 5.1.1 on 2025-05-12 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0006_project_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreApprovedTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("is_valid", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_oficial", models.BooleanField(blank=True, default=False)),
                ("lambda_arn", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="projects.project",
                    ),
                ),
                (
                    "templates",
                    models.ManyToManyField(
                        related_name="agents", to="agents.preapprovedtemplate"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "project")},
            },
        ),
        migrations.CreateModel(
            name="IntegratedAgent",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.TextField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrateds",
                        to="agents.agent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrated_agents",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("agent", "project")},
            },
        ),
    ]
