# Generated by Django 5.1.1 on 2025-05-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="integratedagent",
            old_name="external_id",
            new_name="client_secret",
        ),
        migrations.AddField(
            model_name="integratedagent",
            name="lambda_arn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
