# Generated by Django 5.1.1 on 2025-05-18 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_rename_external_id_integratedagent_client_secret_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="credentials",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=8192)),
                ("placeholder", models.CharField(max_length=255, null=True)),
                ("is_confidential", models.BooleanField(default=False)),
                (
                    "integrated_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="agents.integratedagent",
                    ),
                ),
            ],
            options={
                "unique_together": {("key", "integrated_agent")},
            },
        ),
    ]
