# Generated by Django 5.1.1 on 2025-05-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_rename_external_id_integratedagent_client_secret_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preapprovedtemplate",
            name="metadata",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="preapprovedtemplate",
            name="start_condition",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="preapprovedtemplate",
            name="name",
            field=models.CharField(),
        ),
    ]
