# Generated by Django 5.1.1 on 2025-05-20 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_preapprovedtemplate_metadata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integratedagent",
            name="client_secret",
        ),
    ]
