# Generated by Django 5.1.1 on 2025-05-21 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_remove_integratedagent_client_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integratedagent",
            name="lambda_arn",
        ),
    ]
