# Generated by Django 5.1.1 on 2025-05-21 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_agent_credentials_credential"),
        ("agents", "0005_remove_integratedagent_lambda_arn"),
    ]

    operations = []
