# Generated by Django 5.1.1 on 2025-05-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0006_merge_20250521_1449"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="preapprovedtemplate",
            name="display_name",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
