# Generated by Django 5.1.1 on 2025-05-22 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0007_agent_description_preapprovedtemplate_display_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="templates",
        ),
        migrations.AddField(
            model_name="agent",
            name="slug",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="preapprovedtemplate",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="preapprovedtemplate",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
