# Generated by Django 5.1.1 on 2025-05-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0008_remove_agent_templates_agent_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integratedagent",
            name="channel_uuid",
            field=models.UUIDField(default="5009500a-9aa5-4332-8c7d-b7af33f0c546"),
            preserve_default=False,
        ),
    ]
