# Generated by Django 5.1.1 on 2025-05-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0008_remove_agent_templates_agent_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integratedagent",
            name="channel_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
