# Generated by Django 5.1.1 on 2025-05-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0009_integratedagent_channel_uuid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="integratedagent",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="integratedagent",
            name="is_active",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
