# Generated by Django 5.1.1 on 2025-05-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0010_alter_integratedagent_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integratedagent",
            name="is_active",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
