# Generated by Django 5.1.1 on 2025-05-23 20:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0011_alter_integratedagent_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="integratedagent",
            name="ignore_templates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="preapprovedtemplate",
            name="slug",
            field=models.CharField(null=True),
        ),
    ]
