# Generated by Django 5.1.1 on 2025-05-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0011_alter_integratedagent_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integratedagent",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
