# Generated by Django 5.1.1 on 2025-05-23 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0012_alter_integratedagent_is_active"),
        ("agents", "0012_integratedagent_ignore_templates_and_more"),
    ]

    operations = []
