# Generated by Django 5.1.1 on 2025-05-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0014_alter_integratedagent_ignore_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="language",
            field=models.CharField(default="pt_BR", max_length=5),
        ),
    ]
