# Generated by Django 5.1.1 on 2025-05-28 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0014_alter_integratedagent_ignore_templates"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="agent",
            unique_together=set(),
        ),
    ]
