# Generated by Django 5.1.1 on 2025-05-28 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0015_agent_language"),
        ("agents", "0015_alter_agent_unique_together"),
    ]

    operations = []
