# Generated by Django 5.1.1 on 2025-05-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0015_agent_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="integratedagent",
            name="contact_percentage",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
