# Generated by Django 5.1.1 on 2025-05-29 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0016_integratedagent_contact_percentage"),
        ("agents", "0016_merge_20250528_1752"),
    ]

    operations = []
