# Generated by Django 5.1.1 on 2025-05-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0017_merge_20250530_1005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integratedagent",
            name="contact_percentage",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
