# Generated by Django 5.1.1 on 2025-05-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0018_alter_integratedagent_contact_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="integratedagent",
            name="config",
            field=models.JSONField(default=dict),
        ),
    ]
