# Generated by Django 5.1.1 on 2025-06-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0019_integratedagent_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="examples",
            field=models.JSONField(default=list, null=True),
        ),
    ]
