# Generated by Django 5.1.1 on 2025-06-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0019_integratedagent_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="integratedagent",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
