# Generated by Django 5.1.1 on 2025-07-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0020_agent_examples"),
    ]

    operations = [
        migrations.AddField(
            model_name="integratedagent",
            name="global_rule_code",
            field=models.TextField(null=True),
        ),
    ]
