# Generated by Django 5.1.1 on 2025-07-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0021_integratedagent_global_rule_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="integratedagent",
            name="global_rule_prompt",
            field=models.TextField(null=True),
        ),
    ]
