# Generated by Django 5.1.1 on 2025-09-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0022_integratedagent_global_rule_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="integratedagent",
            name="parent_agent_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
