# Generated by Django 5.1.1 on 2025-10-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0023_integratedagent_parent_agent_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="preapprovedtemplate",
            name="config",
            field=models.JSONField(default=dict),
        ),
    ]
