# Generated by Django 5.1.1 on 2026-04-24 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0024_preapprovedtemplate_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="integratedagent",
            name="broadcasts_delivered",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="integratedagent",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
