# Generated by Django 5.2.16 on 2026-08-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0029_integratedagent_integer_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="integratedagent",
            name="first_successful_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
