# Generated by Django 5.1 on 2024-09-27 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="organization_name",
        ),
    ]
