# Generated by Django 5.1 on 2024-09-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_remove_project_organization_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="organization_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
