# Generated by Django 5.1.1 on 2024-11-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_organization_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="vtex_account",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
