# Generated by Django 5.1.1 on 2025-03-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_vtex_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="config",
            field=models.JSONField(default=dict),
        ),
    ]
