# Generated by Django 5.1.1 on 2025-09-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_project_projects_pr_uuid_75bd24_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
