# Generated by Django 5.1.1 on 2026-02-13 21:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_project_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("vtex_account", models.CharField(db_index=True, max_length=100)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "current_page",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("completed", models.BooleanField(default=False)),
                ("progress", models.IntegerField(default=0)),
                (
                    "current_step",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "crawler_result",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "project",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
