# Generated by Django 5.1.1 on 2026-02-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_projectonboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="language",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
