# Generated by Django 5.1.1 on 2026-02-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_project_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectonboarding",
            name="failed",
            field=models.BooleanField(default=False),
        ),
    ]
