# Generated by Django 5.2.12 on 2026-03-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_projectonboarding_failed"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectonboarding",
            name="skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="projectonboarding",
            name="vtex_account",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
