# Generated by Django 5.1.1 on 2026-04-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_projectonboarding_skipped_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_blocked",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
