# Generated by Django 5.1.1 on 2026-06-19 17:14

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_project_is_blocked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelManagers(
            name="project",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
