# Generated by Django 5.1.1 on 2026-06-19 19:45

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_alter_project_options_alter_project_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectonboarding",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelManagers(
            name="projectonboarding",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="projectonboarding",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="projectonboarding",
            name="vtex_account",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name="projectonboarding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("vtex_account",),
                name="projects_onboarding_unique_active_vtex_account",
            ),
        ),
    ]
