(function (d, s, u, w, v) {
if (w[v]) { return; } else { w[v] = !0; }
let h = d.getElementsByTagName(s)[0], k = d.createElement(s);
k.onload = function () {
    let l = d.createElement(s); l.src = u; l.async = true;
    h.parentNode.insertBefore(l, k.nextSibling);
};
k.async = true; k.src = '<CDN_URL>';
h.parentNode.insertBefore(k, h);
})(document, 'script', '<SCRIPT_URL>', window, 'isWeniWebChatAlreadyInserted');
