# Generated by Django 5.0.7 on 2024-08-05 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("actions", models.JSONField(null=True)),
                ("name", models.TextField()),
                ("ocupation", models.TextField()),
                (
                    "personality",
                    models.TextField(
                        choices=[
                            ("Amigável", "Amigável"),
                            ("Cooperativo", "Cooperativo"),
                            ("Extrovertido", "Extrovertido"),
                            ("Generoso", "Generoso"),
                            ("Relaxado", "Relaxado"),
                            ("Organizado", "Organizado"),
                            ("Sistemático", "Sistemático"),
                            ("Inovador", "Inovador"),
                            ("Criativo", "Criativo"),
                            ("Intelectual", "Intelectual"),
                        ],
                        default="Amigável",
                    ),
                ),
                ("instructions", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="when are created the new feature",
                    ),
                ),
                ("description", models.TextField(null=True)),
                ("name", models.CharField(max_length=256)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("category", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="FeatureVersion",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("definition", models.JSONField()),
                ("parameters", models.JSONField(blank=True, null=True)),
                ("version", models.CharField(default="1.0", max_length=10)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "brain",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="features.brain",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="features.feature",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegratedFeature",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("parameters", models.JSONField(default=dict, null=True)),
                ("integrated_on", models.DateField(auto_now_add=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrated_features",
                        to="features.feature",
                    ),
                ),
                (
                    "feature_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrated_features",
                        to="features.featureversion",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrated_features",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrated_features",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField()),
                ("flow_uuid", models.CharField(max_length=100, null=True)),
                ("name", models.CharField(max_length=256)),
                ("definition", models.JSONField()),
                (
                    "integrated_feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows",
                        to="features.integratedfeature",
                    ),
                ),
            ],
        ),
    ]
