# Generated by Django 5.0.7 on 2024-08-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureversion",
            name="IntelligentAgent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="features.intelligentagent",
            ),
        ),
    ]
