# Generated by Django 5.0.7 on 2024-07-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0002_alter_featureversion_brain"),
    ]

    operations = [
        migrations.AddField(
            model_name="brain",
            name="names",
            field=models.JSONField(null=True),
        ),
    ]
