# Generated by Django 5.1 on 2024-08-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0002_alter_featureversion_intelligentagent"),
    ]

    operations = [
        migrations.AddField(
            model_name="integratedfeature",
            name="sectors",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
