# Generated by Django 5.1 on 2024-08-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0003_integratedfeature_sectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureversion",
            name="sectors",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
