# Generated by Django 5.0.7 on 2024-08-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0003_brain_names"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brain",
            old_name="names",
            new_name="actions",
        ),
        migrations.AddField(
            model_name="brain",
            name="instructions",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="brain",
            name="name",
            field=models.TextField(default="teste"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="brain",
            name="ocupation",
            field=models.TextField(default="teste"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="brain",
            name="personality",
            field=models.TextField(
                choices=[
                    ("Amigável", "Amigável"),
                    ("Cooperativo", "Cooperativo"),
                    ("Extrovertido", "Extrovertido"),
                    ("Generoso", "Generoso"),
                    ("Relaxado", "Relaxado"),
                    ("Organizado", "Organizado"),
                    ("Sistemático", "Sistemático"),
                    ("Inovador", "Inovador"),
                    ("Criativo", "Criativo"),
                    ("Intelectual", "Intelectual"),
                ],
                default="Amigável",
            ),
        ),
    ]
