# Generated by Django 5.1 on 2024-08-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0004_featureversion_sectors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featureversion",
            name="IntelligentAgent",
        ),
        migrations.AddField(
            model_name="feature",
            name="dependencies",
            field=models.ManyToManyField(null=True, to="features.feature"),
        ),
        migrations.AddField(
            model_name="feature",
            name="feature_type",
            field=models.CharField(
                choices=[("FEATURE", "Feature"), ("FUNCTION", "Function")],
                default="Feature",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="integratedfeature",
            name="action_base_flow",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="integratedfeature",
            name="action_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="integratedfeature",
            name="action_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="featureversion",
            name="parameters",
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.DeleteModel(
            name="IntelligentAgent",
        ),
    ]
