# Generated by Django 5.1 on 2024-08-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0005_remove_featureversion_intelligentagent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature",
            old_name="dependencies",
            new_name="functions",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="category",
        ),
        migrations.AlterField(
            model_name="feature",
            name="feature_type",
            field=models.CharField(
                choices=[("FEATURE", "Feature"), ("FUNCTION", "Function")],
                default="FEATURE",
                max_length=100,
            ),
        ),
    ]
