# Generated by Django 5.1 on 2024-09-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0007_alter_integratedfeature_parameters_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integratedfeature",
            name="action_name",
        ),
        migrations.RemoveField(
            model_name="integratedfeature",
            name="action_prompt",
        ),
        migrations.AddField(
            model_name="featureversion",
            name="action_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="featureversion",
            name="action_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="featureversion",
            name="action_types",
            field=models.TextField(
                blank=True,
                choices=[
                    ("PERSONALIZADO", "Personalizado"),
                    ("VOLTAR AO MENU", "Voltar ao Menu"),
                    ("INTEGRAÇÕES GERAIS", "Interações gerais"),
                    ("CONFIGURAR COMUNICAÇÕES", "Configurar comunicações"),
                    ("DESPEDIDA", "Despedida"),
                    ("SAC/FALE CONOSCO", "SAC/Fale conosco"),
                    ("INDIQUE E GANHE", "Indique e Ganhe"),
                    ("TROCA E DEVOLUÇÃO", "Troca e Devolução"),
                    ("STATUS DO PEDIDO", "Status do Pedido"),
                ],
                default="Custom",
                null=True,
            ),
        ),
    ]
