# Generated by Django 5.1 on 2024-09-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0008_remove_integratedfeature_action_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureversion",
            name="action_type_brain",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="featureversion",
            name="action_types",
            field=models.TextField(
                blank=True,
                choices=[
                    ("PERSONALIZADO", "Personalizado"),
                    ("VOLTAR AO MENU", "Voltar ao Menu"),
                    ("INTEGRAÇÕES GERAIS", "Interações gerais"),
                    ("CONFIGURAR COMUNICAÇÕES", "Configurar comunicações"),
                    ("DESPEDIDA", "Despedida"),
                    ("SAC/FALE CONOSCO", "SAC/Fale conosco"),
                    ("INDIQUE E GANHE", "Indique e Ganhe"),
                    ("TROCA E DEVOLUÇÃO", "Troca e Devolução"),
                    ("STATUS DO PEDIDO", "Status do Pedido"),
                ],
                default="PERSONALIZADO",
                null=True,
            ),
        ),
    ]
