# Generated by Django 5.1 on 2024-09-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0009_featureversion_action_type_brain_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="featureversion",
            old_name="parameters",
            new_name="globals_values",
        ),
        migrations.RenameField(
            model_name="integratedfeature",
            old_name="parameters",
            new_name="globals_values",
        ),
    ]
