# Generated by Django 5.1 on 2024-09-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0010_rename_parameters_featureversion_globals_values_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="category",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("PASSIVE", "Passive")],
                default="PASSIVE",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="disclaimer",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="feature",
            name="documentation_url",
            field=models.TextField(null=True),
        ),
    ]
