# Generated by Django 5.1.1 on 2024-10-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0011_feature_category_feature_disclaimer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Function",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("features.feature",),
        ),
        migrations.RemoveField(
            model_name="integratedfeature",
            name="action_base_flow",
        ),
    ]
