# Generated by Django 5.1.1 on 2024-10-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0012_function_remove_integratedfeature_action_base_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureversion",
            name="action_base_flow_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="featureversion",
            name="action_base_flow_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
