# Generated by Django 5.1.1 on 2024-10-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0013_featureversion_action_base_flow_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("development", "Development"),
                    ("testing", "Testing"),
                    ("ready", "Ready"),
                ],
                default="development",
                max_length=20,
                null=True,
                verbose_name="Status of feature",
            ),
        ),
        migrations.AlterField(
            model_name="featureversion",
            name="action_types",
            field=models.TextField(
                blank=True,
                choices=[
                    ("PERSONALIZADO", "Personalizado"),
                    ("VOLTAR AO MENU", "Voltar ao Menu"),
                    ("INTERAÇÕES GERAIS", "Interações gerais"),
                    ("CONFIGURAR COMUNICAÇÕES", "Configurar comunicações"),
                    ("DESPEDIDA", "Despedida"),
                    ("SAC/FALE CONOSCO", "SAC/Fale conosco"),
                    ("INDIQUE E GANHE", "Indique e Ganhe"),
                    ("TROCA E DEVOLUÇÃO", "Troca e Devolução"),
                    ("STATUS DO PEDIDO", "Status do Pedido"),
                    ("CUMPRIMENTOS", "Cumprimentos"),
                    ("COMPRAS DE PRODUTOS", "Compras de Produtos"),
                    ("TÓPICOS SENSÍVEIS", "Tópicos sensíveis"),
                    ("MÍDIAS E LOCALIZAÇÃO", "Mídias e Localização"),
                    ("ENVIO DE CARRINHO DO WHATSAPP", "Envio de Carrinho do Whatsapp"),
                    ("CONTROLE DO AGENTE", "Controle do agente"),
                ],
                default="PERSONALIZADO",
                null=True,
            ),
        ),
    ]
