# Generated by Django 5.1.1 on 2024-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0014_feature_status_alter_featureversion_action_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="can_vtex_integrate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feature",
            name="config",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="integratedfeature",
            name="created_by_vtex",
            field=models.BooleanField(default=False),
        ),
    ]
