# Generated by Django 5.1.1 on 2025-01-17 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0016_integratedfeature_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integratedfeature",
            name="feature_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrated_features",
                to="features.featureversion",
            ),
        ),
    ]
