# Generated by Django 5.1.1 on 2025-01-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0016_integratedfeature_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="code",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
