# Generated by Django 5.1.1 on 2025-05-08 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.UUID("f8dc9ecd-16b5-4087-9398-c71a20fe45d6"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("start_condition", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ReadTemplateUseCase",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="templates.template",
                    ),
                ),
            ],
            bases=("templates.template",),
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(unique=True)),
                ("integrations_app_uuid", models.UUIDField()),
                ("project_uuid", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APPROVED", "Approved"),
                            ("IN_APPEAL", "In Appeal"),
                            ("PENDING", "Pending"),
                            ("REJECTED", "Rejected"),
                            ("PENDING_DELETION", "Pending Deletion"),
                            ("DELETED", "Deleted"),
                            ("DISABLED", "Disabled"),
                            ("LOCKED", "Locked"),
                        ],
                        default="PENDING",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.UUID("cf765352-1afe-4aa5-bd09-ddea7ab6dd90"),
                        editable=False,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="templates.template",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="template",
            name="current_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_of",
                to="templates.version",
            ),
        ),
    ]
