# Generated by Django 5.1.1 on 2025-05-09 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_project_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("start_condition", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(unique=True)),
                ("integrations_app_uuid", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APPROVED", "Approved"),
                            ("IN_APPEAL", "In Appeal"),
                            ("PENDING", "Pending"),
                            ("REJECTED", "Rejected"),
                            ("PENDING_DELETION", "Pending Deletion"),
                            ("DELETED", "Deleted"),
                            ("DISABLED", "Disabled"),
                            ("LOCKED", "Locked"),
                        ],
                        default="PENDING",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_versions",
                        to="projects.project",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="templates.template",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="template",
            name="current_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_of",
                to="templates.version",
            ),
        ),
    ]
