# Generated by Django 5.1.1 on 2025-05-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="rule_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
