# Generated by Django 5.1.1 on 2025-05-12 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
        ("templates", "0002_template_rule_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="integrated_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agents.integratedagent",
            ),
        ),
    ]
