# Generated by Django 5.1.1 on 2025-05-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0003_template_integrated_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
