# Generated by Django 5.1.1 on 2025-05-20 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_preapprovedtemplate_metadata_and_more"),
        ("templates", "0003_template_integrated_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="integrated_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="agents.integratedagent",
            ),
        ),
    ]
