# Generated by Django 5.1.1 on 2025-05-22 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0004_template_metadata"),
        ("templates", "0005_alter_template_integrated_agent"),
    ]

    operations = []
