# Generated by Django 5.1.1 on 2025-05-23 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0009_integratedagent_channel_uuid"),
        ("templates", "0006_merge_20250522_1220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="integrated_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="agents.integratedagent",
            ),
        ),
    ]
