# Generated by Django 5.1.1 on 2025-05-23 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0009_integratedagent_channel_uuid"),
        ("templates", "0007_alter_template_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="start_condition",
        ),
        migrations.AddField(
            model_name="template",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="agents.preapprovedtemplate",
            ),
        ),
    ]
