# Generated by Django 5.1.1 on 2025-05-23 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0007_alter_template_integrated_agent"),
        ("templates", "0008_remove_template_start_condition_template_parent"),
    ]

    operations = []
