# Generated by Django 5.1.1 on 2025-05-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0009_merge_20250523_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="needs_button_edit",
            field=models.BooleanField(default=False),
        ),
    ]
