# Generated by Django 5.1.1 on 2025-05-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0010_template_needs_button_edit"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
