# Generated by Django 5.1.1 on 2025-06-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0011_template_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="display_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="start_condition",
            field=models.TextField(blank=True, null=True),
        ),
    ]
