# Generated by Django 5.1.1 on 2025-06-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0011_template_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
