# Generated by Django 5.1.1 on 2025-06-27 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0012_template_deleted_at"),
        ("templates", "0012_template_display_name_template_start_condition"),
    ]

    operations = []
