# Generated by Django 5.1.1 on 2025-07-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0013_merge_20250627_0904"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="variables",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
