# Generated by Django 5.1.1 on 2025-08-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0014_template_variables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="template_name",
            field=models.CharField(),
        ),
    ]
