# Generated by Django 5.1.1 on 2025-07-28 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0014_template_variables"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="template",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
