# Generated by Django 5.1.1 on 2025-10-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0015_alter_version_template_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
