# Generated by Django 5.1.1 on 2026-05-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0016_template_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APPROVED", "Approved"),
                    ("IN_APPEAL", "In Appeal"),
                    ("PENDING", "Pending"),
                    ("REJECTED", "Rejected"),
                    ("PENDING_DELETION", "Pending Deletion"),
                    ("DELETED", "Deleted"),
                    ("DISABLED", "Disabled"),
                    ("LOCKED", "Locked"),
                    ("PAUSED", "Paused"),
                    ("FLAGGED", "Flagged"),
                ],
                default="PENDING",
            ),
        ),
    ]
