# Generated by Django 5.1.1 on 2026-05-06 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0025_integratedagent_broadcasts_delivered_and_more"),
        ("projects", "0013_project_is_blocked"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectBroadcastCounter",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="broadcast_counter",
                        serialize=False,
                        to="projects.project",
                    ),
                ),
                ("total_delivered", models.PositiveBigIntegerField(default=0)),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BroadcastMessage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("broadcast_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "external_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "template_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "template_version",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("flows_template_uuid", models.UUIDField(blank=True, null=True)),
                ("channel_uuid", models.UUIDField(blank=True, null=True)),
                (
                    "contact_urn",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initializing", "Initializing"),
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("wired", "Wired"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("errored", "Errored"),
                            ("failed", "Failed"),
                            ("unknown", "Unknown"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("status_updated_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("last_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integrated_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcast_messages",
                        to="agents.integratedagent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_messages",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["broadcast_id"], name="broadcasts__broadca_b35af2_idx"
                    ),
                    models.Index(
                        fields=["external_message_id"],
                        name="broadcasts__externa_01869e_idx",
                    ),
                    models.Index(
                        fields=["project", "created_at"],
                        name="broadcasts__project_597900_idx",
                    ),
                    models.Index(
                        fields=["integrated_agent", "created_at"],
                        name="broadcasts__integra_383b01_idx",
                    ),
                    models.Index(
                        fields=["project", "status"],
                        name="broadcasts__project_7af8e5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("broadcast_id__isnull", False)),
                        fields=("broadcast_id",),
                        name="broadcasts_broadcast_id_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("external_message_id__isnull", False)),
                        fields=("external_message_id",),
                        name="broadcasts_external_message_id_unique",
                    ),
                ],
            },
        ),
    ]
