# Generated by Django 5.1.1 on 2026-05-07 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0025_integratedagent_broadcasts_delivered_and_more"),
        ("broadcasts", "0001_initial"),
        ("projects", "0013_project_is_blocked"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("order_id", models.CharField(max_length=255)),
                (
                    "order_form_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                ("converted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="broadcastmessage",
            name="order_form_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="broadcastmessage",
            name="order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="broadcastmessage",
            index=models.Index(
                fields=["project", "order_form_id"],
                name="broadcasts__project_3a531b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="broadcastmessage",
            index=models.Index(
                fields=["project", "order_id"], name="broadcasts__project_ac9636_idx"
            ),
        ),
        migrations.AddField(
            model_name="broadcastconversion",
            name="integrated_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="broadcast_conversions",
                to="agents.integratedagent",
            ),
        ),
        migrations.AddField(
            model_name="broadcastconversion",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broadcast_conversions",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="broadcastconversion",
            index=models.Index(
                fields=["project", "converted_at"],
                name="broadcasts__project_701313_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="broadcastconversion",
            index=models.Index(
                fields=["integrated_agent", "converted_at"],
                name="broadcasts__integra_102e8e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="broadcastconversion",
            index=models.Index(
                fields=["project", "order_form_id"],
                name="broadcasts__project_173f49_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="broadcastconversion",
            constraint=models.UniqueConstraint(
                fields=("project", "order_id"),
                name="broadcast_conversions_project_order_unique",
            ),
        ),
    ]
