# Generated by Django 5.1.1 on 2026-05-08 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broadcasts", "0003_broadcastmessage_integer_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcastconversion",
            name="broadcast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversions",
                to="broadcasts.broadcastmessage",
            ),
        ),
    ]
