# Generated by Django 5.1.1 on 2026-06-11 16:26

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0013_project_is_blocked"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("version", models.CharField(max_length=50, unique=True)),
                ("template_name", models.CharField(max_length=255)),
                (
                    "default_checkbox_label_text",
                    models.TextField(blank=True, default=""),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContractAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("user_id", models.UUIDField()),
                ("email_at_acceptance", models.EmailField(max_length=254)),
                ("company_name", models.CharField(max_length=256)),
                ("user_name", models.CharField(max_length=256)),
                ("vtex_account", models.CharField(max_length=100)),
                (
                    "accepted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("accepted_at_local_offset", models.CharField(max_length=6)),
                ("contract_version", models.CharField(max_length=50)),
                ("contract_document_key", models.CharField(max_length=1024)),
                ("plan_id", models.UUIDField(blank=True, null=True)),
                ("plan_snapshot", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("session_id", models.CharField(max_length=255)),
                (
                    "acceptance_method",
                    models.CharField(
                        choices=[
                            ("checkbox", "Checkbox"),
                            ("click_agree", "Click agree"),
                        ],
                        default="checkbox",
                        max_length=20,
                    ),
                ),
                ("checkbox_label_text", models.TextField()),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("geo_country", models.CharField(blank=True, max_length=2, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_acceptances",
                        to="projects.project",
                    ),
                ),
                (
                    "contract_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="contracts.contracttemplate",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project"], name="contracts_c_project_8c0042_idx"
                    ),
                    models.Index(
                        fields=["user_id"], name="contracts_c_user_id_659b88_idx"
                    ),
                    models.Index(
                        fields=["contract_version"],
                        name="contracts_c_contrac_e7c9fa_idx",
                    ),
                    models.Index(
                        fields=["-accepted_at"], name="contracts_c_accepte_4d7574_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("acceptance_method__in", ("checkbox", "click_agree"))
                        ),
                        name="ca_acceptance_method_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "accepted_at_local_offset__regex",
                                "^[+-][0-9]{2}:[0-9]{2}$",
                            )
                        ),
                        name="ca_local_offset_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("geo_country__isnull", True),
                            (
                                "geo_country",
                                django.db.models.functions.text.Upper("geo_country"),
                            ),
                            _connector="OR",
                        ),
                        name="ca_geo_country_upper",
                    ),
                ],
            },
        ),
    ]
