"""
Django settings for retail project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import environ
import sentry_sdk
import urllib

from pathlib import Path

from sentry_sdk.integrations.django import DjangoIntegration

from corsheaders.defaults import default_headers, default_methods

# Celery Beat Schedule
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# environ settings
ENV_PATH = os.path.join(BASE_DIR, ".env")

if os.path.exists(ENV_PATH):
    environ.Env.read_env(env_file=ENV_PATH)

env = environ.Env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

SERVICE_HOST = env.str("SERVICE_HOST", default="localhost")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

CSRF_TRUSTED_ORIGINS = [f"https://*.{SERVICE_HOST}"]

SENTRY_DSN = env.str("SENTRY_DSN", default="")

sentry_sdk.init(
    dsn=SENTRY_DSN,
    integrations=[DjangoIntegration()],
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

# Application definition

INSTALLED_APPS = [
    "retail.admin",
    "mozilla_django_oidc",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "weni.eda.django.eda_app",
    "corsheaders",
    "retail.projects",
    "retail.features",
    "retail.integrations",
    "retail.healthcheck",
    "retail.internal",
    "rest_framework",
    "drf_yasg",
    "retail.vtex",
    "retail.templates",
    "retail.agents",
    "retail.broadcasts",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = "retail.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "retail.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = dict(default=env.db(var="DATABASE_URL"))


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = env.str("LANGUAGE_CODE", default="en-us")

TIME_ZONE = env.str("TIME_ZONE", default="America/Maceio")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "static"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Event Driven Architecture configurations

USE_EDA = env.bool("USE_EDA", default=False)

# Per-project cap of delivered broadcasts; on reach, triggers trial suspension.
RETAIL_TRIAL_BROADCAST_LIMIT = env.int("RETAIL_TRIAL_BROADCAST_LIMIT", default=100)

ACTION_TYPES = env.json("ACTION_TYPES", default={})

# CORS configurations

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOW_CREDENTIALS = env.bool("CORS_ALLOW_CREDENTIALS", default=True)
CORS_ALLOW_HEADERS = env.list("CORS_ALLOW_HEADERS", default=default_headers) + (
    "project-uuid",
)
CORS_ALLOW_METHODS = env.list("CORS_ALLOW_METHODS", default=default_methods)

if USE_EDA:
    EDA_CONSUMERS_HANDLE = "retail.event_driven.handle.handle_consumers"
    EDA_BROKER_HOST = env("EDA_BROKER_HOST", default="localhost")
    EDA_VIRTUAL_HOST = env("EDA_VIRTUAL_HOST", default="/")
    EDA_BROKER_PORT = env.int("EDA_BROKER_PORT", default=5672)
    EDA_BROKER_USER = env("EDA_BROKER_USER", default="guest")
    EDA_BROKER_PASSWORD = env("EDA_BROKER_PASSWORD", default="guest")

USE_OIDC = env.bool("USE_OIDC")

if USE_OIDC:
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"].append(
        "mozilla_django_oidc.contrib.drf.OIDCAuthentication"
    )

    OIDC_RP_CLIENT_ID = env.str("OIDC_RP_CLIENT_ID")
    OIDC_RP_CLIENT_SECRET = env.str("OIDC_RP_CLIENT_SECRET")
    OIDC_OP_AUTHORIZATION_ENDPOINT = env.str("OIDC_OP_AUTHORIZATION_ENDPOINT")
    OIDC_OP_TOKEN_ENDPOINT = env.str("OIDC_OP_TOKEN_ENDPOINT")
    OIDC_OP_USER_ENDPOINT = env.str("OIDC_OP_USER_ENDPOINT")
    OIDC_OP_JWKS_ENDPOINT = env.str("OIDC_OP_JWKS_ENDPOINT")
    OIDC_RP_SIGN_ALGO = env.str("OIDC_RP_SIGN_ALGO", default="RS256")
    OIDC_DRF_AUTH_BACKEND = "retail.internal.backends.WeniOIDCAuthenticationBackend"
    OIDC_RP_SCOPES = env.str("OIDC_RP_SCOPES", default="openid email")

INTEGRATIONS_REST_ENDPOINT = env.str("INTEGRATIONS_REST_ENDPOINT")

FLOWS_REST_ENDPOINT = env.str("FLOWS_REST_ENDPOINT")

EMAILS_CAN_TESTING = env.str("EMAILS_CAN_TESTING", "").split(",")

# Redis
REDIS_URL = env.str("REDIS_URL", default="redis://localhost:6379")


# Celery
CELERY_BROKER_URL = env.str("CELERY_BROKER_URL", default=REDIS_URL)
CELERY_RESULT_BACKEND = None
CELERY_TASK_IGNORE_RESULT = True
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Maximum number of executions a single flush tick drains from the
# Redis ZSET. Caps per-tick S3 + DB cost; remaining entries are
# picked up on the next tick.
AGENT_EXECUTION_FLUSH_BATCH_SIZE = env.int(
    "AGENT_EXECUTION_FLUSH_BATCH_SIZE", default=500
)

# Maximum number of AgentExecution rows the retention sweep deletes
# per iteration. Bounds the per-statement runtime so the daily
# cleanup task does not hit Postgres ``statement_timeout`` or the
# Celery soft/hard timeout on tables with millions of rows. The use
# case loops until no rows older than the retention horizon remain.
AGENT_EXECUTION_CLEANUP_BATCH_SIZE = env.int(
    "AGENT_EXECUTION_CLEANUP_BATCH_SIZE", default=5000
)

# Beat cadence for ``task_flush_execution_logs``. Each tick drains
# ready entries from the queue and (every Nth tick) runs the SQL
# stuck sweep. Empty ticks are no-ops.
AGENT_EXECUTION_FLUSH_INTERVAL_SECONDS = env.float(
    "AGENT_EXECUTION_FLUSH_INTERVAL_SECONDS", default=1.0
)

# An execution sits in the flush queue with a deadline of
# ``now + max_wait_seconds``. Reaching a terminal status bumps the
# deadline to ``now`` so the next flush picks it up immediately. If
# the deadline expires without a terminal status, the flush
# force-finalises the row as ``error='Execution timed out'``.
AGENT_EXECUTION_MAX_WAIT_SECONDS = env.int(
    "AGENT_EXECUTION_MAX_WAIT_SECONDS", default=600
)

# Every Nth flush tick the same task additionally runs a SQL sweep
# for rows still ``processing`` past the stuck threshold. At the
# default 1s tick interval, ``60`` means "run the sweep once per
# minute".
AGENT_EXECUTION_STUCK_SWEEP_EVERY_N_TICKS = env.int(
    "AGENT_EXECUTION_STUCK_SWEEP_EVERY_N_TICKS", default=60
)

# DB rows still ``processing`` with ``updated_on`` older than this
# threshold are force-finalised by the SQL stuck sweep. Catches the
# rare case where Redis lost the queue entry (eviction, restart) but
# the DB row is still in flight.
AGENT_EXECUTION_STUCK_THRESHOLD_SECONDS = env.int(
    "AGENT_EXECUTION_STUCK_THRESHOLD_SECONDS", default=600
)

# Maximum number of parallel S3 PUT workers the flush task uses for
# trace files. Each PUT is a per-execution write so this is the
# upper bound on concurrent uploads per tick.
AGENT_EXECUTION_S3_PARALLEL_PUTS = env.int(
    "AGENT_EXECUTION_S3_PARALLEL_PUTS", default=10
)

# Dedicated Celery queue for agent-execution maintenance tasks
# (cleanup + flush). Isolating these from the default ``celery``
# queue prevents the high-frequency flush loop from blocking
# unrelated jobs. Requires a worker started with
# ``celery-worker <queue-name>`` consuming this queue.
AGENT_EXECUTION_CELERY_QUEUE = env.str(
    "AGENT_EXECUTION_CELERY_QUEUE", default="agent-executions"
)

CELERY_BEAT_SCHEDULE = {
    "task-cleanup-old-carts": {
        "task": "task_cleanup_old_carts",
        "schedule": crontab(minute=0, hour=2),
    },
    "task-cleanup-old-executions": {
        "task": "task_cleanup_old_executions",
        "schedule": crontab(minute=30, hour=2),
    },
    "task-flush-execution-logs": {
        "task": "task_flush_execution_logs",
        "schedule": AGENT_EXECUTION_FLUSH_INTERVAL_SECONDS,
    },
}

CELERY_TASK_ROUTES = {
    "task_cleanup_old_executions": {"queue": AGENT_EXECUTION_CELERY_QUEUE},
    "task_flush_execution_logs": {"queue": AGENT_EXECUTION_CELERY_QUEUE},
}


# Cache
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}

OIDC_CACHE_TOKEN = env.bool(
    "OIDC_CACHE_TOKEN", default=False
)  # Enable/disable user token caching (default: False).
OIDC_CACHE_TTL = env.int(
    "OIDC_CACHE_TTL", default=600
)  # Time-to-live for cached user tokens (default: 600 seconds).

VTEX_IO_OIDC_RP_CLIENT_SECRET = env.str("VTEX_IO_OIDC_RP_CLIENT_SECRET", "")
VTEX_IO_OIDC_RP_CLIENT_ID = env.str("VTEX_IO_OIDC_RP_CLIENT_ID", "")

# Abandoned Cart timeout in minutes
ABANDONED_CART_COUNTDOWN = env.int("ABANDONED_CART_COUNTDOWN", default=25)

# Endpoint for Nexus service
NEXUS_REST_ENDPOINT = env.str("NEXUS_REST_ENDPOINT", default="")

# Endpoint for code actions service
CODE_ACTIONS_REST_ENDPOINT = env.str("CODE_ACTIONS_REST_ENDPOINT", "")

# Endpoint for Crawler microservice
CRAWLER_REST_ENDPOINT = env.str("CRAWLER_REST_ENDPOINT", "")

# WWC (Weni Web Chat) default profile avatar
WWC_PROFILE_AVATAR_URL = env.str("WWC_PROFILE_AVATAR_URL", "")

# Passive agent UUIDs per channel — JSON dict mapping agent name to UUID
# Format: {"Order Status": "136eb450-...", "Product Concierge": "3e51cf10-...", ...}
PASSIVE_AGENTS_WWC = env.json("PASSIVE_AGENTS_WWC", default={})
PASSIVE_AGENTS_WPP_CLOUD = env.json("PASSIVE_AGENTS_WPP_CLOUD", default={})


# VTEX IO workspace configuration
VTEX_IO_WORKSPACE = env.str("VTEX_IO_WORKSPACE", default="")

# Lambda no token validation
LAMBDA_ALLOWED_ROLES = env.list("LAMBDA_ALLOWED_ROLES", default=[])

USE_LAMBDA = env.bool("USE_LAMBDA", default=False)
USE_S3 = env.bool("USE_S3", default=False)

DOMAIN = env.str("DOMAIN", default="http://localhost:8000")

if USE_LAMBDA:
    LAMBDA_ROLE_ARN = env.str("LAMBDA_ROLE_ARN")
    LAMBDA_RUNTIME = env.str("LAMBDA_RUNTIME")
    LAMBDA_HANDLER = env.str("LAMBDA_HANDLER")
    LAMBDA_REGION = env.str("LAMBDA_REGION")
    LAMBDA_TIMEOUT = env.int("LAMBDA_TIMEOUT", default=60)
    LAMBDA_CODE_GENERATOR = env.str("LAMBDA_CODE_GENERATOR")
    LAMBDA_CODE_GENERATOR_REGION = env.str("LAMBDA_CODE_GENERATOR_REGION")
    LAMBDA_LOG_GROUP = env.str("LAMBDA_LOG_GROUP")

if USE_S3:
    AWS_STORAGE_BUCKET_NAME = env.str("AWS_STORAGE_BUCKET_NAME")

# S3 bucket for storing agent execution traces
# Defaults to AWS_STORAGE_BUCKET_NAME if not specified
EXECUTION_TRACES_BUCKET = env.str(
    "EXECUTION_TRACES_BUCKET",
    default=env.str("AWS_STORAGE_BUCKET_NAME", default=""),
)

# Retention horizon (in days) for AgentExecution rows. The
# task_cleanup_old_executions Celery beat task deletes rows older
# than this. The matching S3 lifecycle rule on the executions/
# prefix of EXECUTION_TRACES_BUCKET is configured outside Django.
AGENT_EXECUTION_RETENTION_DAYS = env.int("AGENT_EXECUTION_RETENTION_DAYS", default=30)

# Webchat Push S3 — bucket used by the VTEX pixel app to load the webchat loader
WEBCHAT_PUSH_S3_BUCKET_NAME = env.str("WEBCHAT_PUSH_S3_BUCKET_NAME", default="")
WEBCHAT_PUSH_S3_REGION = env.str("WEBCHAT_PUSH_S3_REGION", default="")
WEBCHAT_PUSH_S3_ACCESS_KEY_ID = env.str("WEBCHAT_PUSH_S3_ACCESS_KEY_ID", default="")
WEBCHAT_PUSH_S3_SECRET_ACCESS_KEY = env.str(
    "WEBCHAT_PUSH_S3_SECRET_ACCESS_KEY", default=""
)
WEBCHAT_CDN_URL = env.str("WEBCHAT_CDN_URL", default="")

USE_META = env.bool("USE_LAMBDA", default=False)

if USE_META:
    META_SYSTEM_USER_ACCESS_TOKEN = env.str("META_SYSTEM_USER_ACCESS_TOKEN")
    META_VERSION = env.str("META_VERSION", default="v20.0")
    META_API_URL = urllib.parse.urljoin(
        env.str("WHATSAPP_API_URL", default="https://graph.facebook.com/"), META_VERSION
    )

ORDER_STATUS_AGENT_UUID = env.str("ORDER_STATUS_AGENT_UUID", default="")
ABANDONED_CART_AGENT_UUID = env.str("ABANDONED_CART_AGENT_UUID", default="")
ABANDONED_CART_DEFAULT_IMAGE_URL = env.str(
    "ABANDONED_CART_DEFAULT_IMAGE_URL",
    default="https://placehold.co/1200x628/png?text=Your+Product",
)
PAYMENT_RECOVERY_AGENT_UUID = env.str("PAYMENT_RECOVERY_AGENT_UUID", default="")

# Time window (in seconds) to ignore repeated order status events.
# An identical event (same project, agent, order, and current state) arriving
# twice within this window is processed only once. This prevents duplicate
# broadcasts caused by upstream retries.
ORDER_STATUS_DUPLICATE_WINDOW_SECONDS = env.int(
    "ORDER_STATUS_DUPLICATE_WINDOW_SECONDS", default=60
)

CONNECT_REST_ENDPOINT = env.str("CONNECT_REST_ENDPOINT", default="")

# Slack notifications (hire intent)
SLACK_BOT_TOKEN = env.str("SLACK_BOT_TOKEN", default="")
SLACK_LEAD_NOTIFICATION_CHANNEL = env.str("SLACK_LEAD_NOTIFICATION_CHANNEL", default="")

# Path to the JWT public key
JWT_PUBLIC_KEY_PATH = BASE_DIR / "retail" / "jwt_keys" / "public_key.pem"

# The public key is loaded a single time at application startup.
try:
    with open(JWT_PUBLIC_KEY_PATH, "rb") as f:
        JWT_PUBLIC_KEY = f.read()
except FileNotFoundError:
    JWT_PUBLIC_KEY = None

# JWT secret key
JWT_SECRET_KEY = env.str("JWT_SECRET_KEY", default="")

# Datalake server address
DATALAKE_SERVER_ADDRESS = env.str("DATALAKE_SERVER_ADDRESS", default="")

# Temporary configuration to ignore empty carts for specific projects
# This allows projects to bypass empty cart validation during cart abandonment processing
IGNORE_EMPTY_CARTS_FOR_PROJECTS = env.list(
    "IGNORE_EMPTY_CARTS_FOR_PROJECTS", default=[]
)

# Channel that receives onboarding support requests triggered by the
# front-end (Contact support button) so the team can investigate the
# underlying error with full onboarding context.
SLACK_ONBOARDING_ERROR_CHANNEL = env.str("SLACK_ONBOARDING_ERROR_CHANNEL", default="")

# APM

USE_ELASTIC_APM = env.bool("USE_ELASTIC_APM", default=False)

if USE_ELASTIC_APM:
    INSTALLED_APPS.append("elasticapm.contrib.django")
    ELASTIC_APM = {
        "SERVICE_NAME": env.str("APM_SERVICE_NAME", default="retail"),
        "SECRET_TOKEN": env.str("APM_SECRET_TOKEN"),
        "SERVER_URL": env.str("APM_SERVER_URL"),
        "ENVIRONMENT": env.str("APM_SERVICE_ENVIRONMENT", default="production"),
    }

# Logging configuration
LOG_LEVEL = env.str("LOG_LEVEL", default="WARNING")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "retail": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
